### ISSUE TITLE
We would like to store the log files on a separate partition compared to the base of the amq file system

### ISSUE THREAD

**Issue by RobertFloor** [ansible-middleware/amq#206]
##### SUMMARY
In production our audit log files grow pretty fast. We would like to store them on a separate partition compared to the AMQ broker directory  (in our case /opt) We would like to store them at /var/log/amq for example. This variable only stores relative tot the broker root. 
```
|`activemq_logger_filepath` | Path for main logfile relative to instance directory | `/log/artemis.log` |
```

##### ISSUE TYPE
 - Feature Idea

**Comment by RobertFloor** [comment]
Hi would it be possible to merge this pr?

**Comment by RanabirChakraborty** [comment]
The PR is merged now.

**Comment by guidograzioli** [comment]
Fixed by #211

**Comment by RobertFloor** [comment]
So this one is also not yet working unfortunately 
Galaxy 2.3.1

------------------------------------------

activemq_main_log_absolute_path: /var/log/amq-broker/artemis.log
activemq_audit_log_absolute_path: /var/log/amq-broker/audit.log

-----------------------------------------

# Log file appender
appender.log_file.type = RollingFile
appender.log_file.name = log_file
appender.log_file.fileName = ${sys:artemis.instance}/log/artemis.log
appender.log_file.filePattern = ${sys:artemis.instance}/log/artemis.log.%d{yyyy-MM-dd}
appender.log_file.layout.type = PatternLayout
appender.log_file.layout.pattern = %d %-5level [%logger] %msg%n
appender.log_file.policies.type = TimeBasedTriggeringPolicy
appender.log_file.strategy.type=DefaultRolloverStrategy
appender.log_file.strategy.max=2

# Audit log file appender
appender.audit_log_file.type = RollingFile
appender.audit_log_file.name = audit_log_file
appender.audit_log_file.fileName = ${sys:artemis.instance}/log/audit.log
appender.audit_log_file.filePattern = ${sys:artemis.instance}/log/audit.log.%d{yyyy-MM-dd}
appender.audit_log_file.layout.type = PatternLayout
appender.audit_log_file.layout.pattern = %d [AUDIT](%t) %msg%n
appender.audit_log_file.policies.type = TimeBasedTriggeringPolicy
appender.audit_log_file.strategy.type=DefaultRolloverStrategy
appender.audit_log_file.strategy.max=2
# BEGIN ANSIBLE MANAGED BLOCK
appender.console.filter.1.type = RegexFilter
appender.console.filter.1.regex = .*221082.*
appender.console.filter.1.onMatch = DENY
appender.console.filter.1.onMismatch = NEUTRAL
# END ANSIBLE MANAGED BLOCK

**Comment by RobertFloor** [comment]
Ok with the latest version this seems to work the only problem is the files are owned by root instead of amq-broker: 

`
activemq_main_log_absolute_path: /var/log/amq-broker/artemis.log
activemq_audit_log_absolute_path: /var/log/amq-broker/audit.log

appender.audit_log_file.fileName = /var/log/amq-broker/audit.log
appender.audit_log_file.filePattern = /var/log/amq-broker/audit.log.%d{yyyy-MM-dd}.%i

[vpn_floor_r@..nl@log]$ cd amq-broker/
[vpn_floor_r@..nl@amq-broker]$ ll
total 0
drwxr-xr-x. 2 root root 6 May  8 11:28 audit.log
`


Antoher problem this change breaks these settings
`cat amq-broker.service
# Ansible managed
[Unit]
Description=amq-broker Apache ActiveMQ Service
After=network.target
RequiresMountsFor=/mnt/asbf-tst-internal

[Service]
User=amq-broker
Group=amq-broker
Type=forking
EnvironmentFile=-/etc/sysconfig/amq-broker
PIDFile=/opt/amq/amq-broker/data/artemis.pid
ExecStart=/opt/amq/amq-broker/bin/artemis-service start
ExecStop=/opt/amq/amq-broker/bin/artemis-service stop
SuccessExitStatus = 0 143
RestartSec = 120
Restart = on-failure
LimitNOFILE=102642
TimeoutSec=600
ExecStartPost=/usr/bin/timeout 60 sh -c 'tail -n 15 -F /opt/amq/amq-broker/log/artemis.log | sed "/AMQ221010\\\\|AMQ221031\\\\|AMQ221007\\\\|AMQ221109\\\\|AMQ221000/ q" && /bin/sleep 10'


[Install]
WantedBy=multi-user.target`

**Comment by guidograzioli** [comment]
`drwxr-xr-x. 2 root root 6 May 8 11:28 audit.log` is that a _directory_??

for the systemd logfile tail feature, of course that is a problem

**Comment by guidograzioli** [comment]
@RobertFloor if you can test this change is fixing your issue, I'll immediately release, thanks

**Comment by RobertFloor** [comment]
Yes will test it today

**Comment by RobertFloor** [comment]
So when I use this setting 
```
    activemq_main_log_absolute_path: "/var/log/amq-broker/"
```
And I create the directory on the broker

```
ll amq-broker/
total 0
-rw-rw-r--. 1 amq-broker amq-broker 0 May 15 11:17 hello
```

The log4.properties file looks incorrect
```
# Log file appender
appender.log_file.type = RollingFile
appender.log_file.name = log_file
appender.log_file.fileName = /var/log/amq-broker/
appender.log_file.filePattern = /var/log/amq-broker/.%d{yyyy-MM-dd}.%i
```

And I cannot start the broker
```
ERROR StatusConsoleListener RollingFileManager (/var/log/amq-broker/) java.io.FileNotFoundException: /var/log/amq-broker (Is a directory)
 java.io.FileNotFoundException: /var/log/amq-broker (Is a directory)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:158)
        at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:878)
        at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:844)
        at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:146)
        at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:112)
        at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:307)
        at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:144)
        at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:65)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:124)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1162)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1083)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1075)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:679)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:264)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:313)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:631)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:713)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:735)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:260)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:154)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:46)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:197)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:136)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:58)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:32)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:422)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:447)
        at org.apache.activemq.artemis.cli.commands.Configurable.<clinit>(Configurable.java:41)
        at org.apache.activemq.artemis.cli.Artemis.buildCommand(Artemis.java:287)
        at org.apache.activemq.artemis.cli.Artemis.internalExecute(Artemis.java:202)
        at org.apache.activemq.artemis.cli.Artemis.execute(Artemis.java:167)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.activemq.artemis.boot.Artemis.execute(Artemis.java:157)
        at org.apache.activemq.artemis.boot.Artemis.main(Artemis.java:64)
ERROR StatusConsoleListener Could not create plugin of type class org.apache.logging.log4j.core.appender.RollingFileAppender for element RollingFile: java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory@759fad4] unable to create manager for [/var/log/amq-broker/] with data [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$FactoryData@64712be[pattern=/var/log/amq-broker/.%d{yyyy-MM-dd}.%i, append=true, bufferedIO=true, bufferSize=8192, policy=CompositeTriggeringPolicy(policies=[CronTriggeringPolicy(schedule=0 0 0 * * ?), SizeBasedTriggeringPolicy(size=104857600)]), strategy=DefaultRolloverStrategy(min=1, max=5, useMax=true), advertiseURI=null, layout=%d %-5level [%logger] %msg%n, filePermissions=null, fileOwner=null]]
 java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory@759fad4] unable to create manager for [/var/log/amq-broker/] with data [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$FactoryData@64712be[pattern=/var/log/amq-broker/.%d{yyyy-MM-dd}.%i, append=true, bufferedIO=true, bufferSize=8192, policy=CompositeTriggeringPolicy(policies=[CronTriggeringPolicy(schedule=0 0 0 * * ?), SizeBasedTriggeringPolicy(size=104857600)]), strategy=DefaultRolloverStrategy(min=1, max=5, useMax=true), advertiseURI=null, layout=%d %-5level [%logger] %msg%n, filePermissions=null, fileOwner=null]]
        at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:148)
        at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:112)
        at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:307)
        at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:144)
        at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:65)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:124)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1162)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1083)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1075)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:679)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:264)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:313)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:631)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:713)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:735)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:260)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:154)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:46)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:197)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:136)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:58)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:32)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:422)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:447)
        at org.apache.activemq.artemis.cli.commands.Configurable.<clinit>(Configurable.java:41)
        at org.apache.activemq.artemis.cli.Artemis.buildCommand(Artemis.java:287)
        at org.apache.activemq.artemis.cli.Artemis.internalExecute(Artemis.java:202)
        at org.apache.activemq.artemis.cli.Artemis.execute(Artemis.java:167)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.activemq.artemis.boot.Artemis.execute(Artemis.java:157)
        at org.apache.activemq.artemis.boot.Artemis.main(Artemis.java:64)
ERROR StatusConsoleListener Unable to invoke factory method in class org.apache.logging.log4j.core.appender.RollingFileAppender for element RollingFile: java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.RollingFileAppender
 java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.RollingFileAppender
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.findFactoryMethod(PluginBuilder.java:268)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:140)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1162)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1083)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1075)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:679)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:264)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:313)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:631)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:713)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:735)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:260)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:154)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:46)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:197)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:136)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:58)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:32)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:422)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:447)
        at org.apache.activemq.artemis.cli.commands.Configurable.<clinit>(Configurable.java:41)
        at org.apache.activemq.artemis.cli.Artemis.buildCommand(Artemis.java:287)
        at org.apache.activemq.artemis.cli.Artemis.internalExecute(Artemis.java:202)
        at org.apache.activemq.artemis.cli.Artemis.execute(Artemis.java:167)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.activemq.artemis.boot.Artemis.execute(Artemis.java:157)
        at org.apache.activemq.artemis.boot.Artemis.main(Artemis.java:64)
ERROR StatusConsoleListener Null object returned for RollingFile in Appenders.
ERROR StatusConsoleListener Unable to locate appender "log_file" for logger config "root"
```

**Comment by guidograzioli** [comment]
Ah that's expected, since it can be a directory we do not control, when you use absolute paths you will need to create the directory in a pre-task in your playbook. There isn't much we can do about it (except maybe add a preliminary validation check)

**Comment by RanabirChakraborty** [comment]
@RobertFloor, you need to pass the file name as well,l like  **activemq_main_log_absolute_path: "/var/log/amq-broker/artemis.log"** but if you don't include the log name, then this results in a pattern with no base filename, which will cause Log4j to misbehave or throw an error.

**Comment by RobertFloor** [comment]
Ok I will test it again with path and filename

**Comment by RobertFloor** [comment]
```
 cd /var/log/amq-broker/
```
So this works now

```
......amq-broker]$ ll
total 1728
-rw-r--r--. 1 amq-broker amq-broker 140724 May 15 12:04 artemis.log
-rw-r--r--. 1 amq-broker amq-broker 904838 May 15 12:04 audit.log
```

With these settings
```
    activemq_main_log_absolute_path: "/var/log/amq-broker/artemis.log"
    activemq_audit_log_absolute_path: "/var/log/amq-broker/audit.log"
```

This is the log4j.properties (we added some more log4j tasks
```
# Log file appender
appender.log_file.type = RollingFile
appender.log_file.name = log_file
appender.log_file.fileName = /var/log/amq-broker/artemis.log
appender.log_file.filePattern = /var/log/amq-broker/artemis.log.%d{yyyy-MM-dd}.%i
appender.log_file.layout.type = PatternLayout
appender.log_file.layout.pattern = %d %-5level [%logger] %msg%n
appender.log_file.policies.type = Policies
appender.log_file.policies.cron.type = CronTriggeringPolicy
appender.log_file.policies.cron.schedule = 0 0 0 * * ?
appender.log_file.policies.cron.evaluateOnStartup = True
appender.log_file.policies.size.type = SizeBasedTriggeringPolicy
appender.log_file.policies.size.size = 104857600
appender.log_file.strategy.type = DefaultRolloverStrategy
appender.log_file.strategy.max = 5

# Audit log file appender
appender.audit_log_file.type = RollingFile
appender.audit_log_file.name = audit_log_file
appender.audit_log_file.fileName = /var/log/amq-broker/audit.log
appender.audit_log_file.filePattern = /var/log/amq-broker/audit.log.%d{yyyy-MM-dd}.%i
appender.audit_log_file.layout.type = PatternLayout
appender.audit_log_file.layout.pattern = %d [AUDIT](%t) %msg%n
appender.audit_log_file.policies.type = Policies
appender.audit_log_file.policies.cron.type = CronTriggeringPolicy
appender.audit_log_file.policies.cron.schedule = 0 0 0 * * ?
appender.audit_log_file.policies.cron.evaluateOnStartup = True
appender.audit_log_file.policies.size.type = SizeBasedTriggeringPolicy
appender.audit_log_file.policies.size.size = 104857600
appender.audit_log_file.strategy.type = DefaultRolloverStrategy
appender.audit_log_file.strategy.max = 5
# BEGIN ANSIBLE MANAGED BLOCK
# remove prometheus errors
appender.console.filter.1.type = RegexFilter
appender.console.filter.1.regex = .*221082.*
appender.console.filter.1.onMatch = DENY
appender.console.filter.1.onMismatch = NEUTRAL
# Add TimeBasedTriggeringPolicy for log files
appender.log_file.policies.timebased.type = TimeBasedTriggeringPolicy
# Delete old Artemis log files
appender.log_file.strategy.action.type = Delete
appender.log_file.strategy.action.basePath = ${sys:artemis.instance}/log/
appender.log_file.strategy.action.maxDepth = 1
appender.log_file.strategy.action.IfFileName.type = IfFileName
appender.log_file.strategy.action.IfFileName.glob = artemis.log.*
appender.log_file.strategy.action.IfFileName.IfLastModified.type = IfLastModified
appender.log_file.strategy.action.IfFileName.IfLastModified.age = 3d
# Add TimeBasedTriggeringPolicy for audit log files
appender.audit_log_file.policies.timebased.type = TimeBasedTriggeringPolicy
# Delete old Audit log files
appender.audit_log_file.strategy.action.type = Delete
appender.audit_log_file.strategy.action.basePath = ${sys:artemis.instance}/log/
appender.audit_log_file.strategy.action.maxDepth = 1
appender.audit_log_file.strategy.action.IfFileName.type = IfFileName
appender.audit_log_file.strategy.action.IfFileName.glob = audit.log.*
appender.audit_log_file.strategy.action.IfFileName.IfLastModified.type = IfLastModified
appender.audit_log_file.strategy.action.IfFileName.IfLastModified.age = 3d
# END ANSIBLE MANAGED BLOCK
```

And the systemd service file
```
# Ansible managed
[Unit]
Description=amq-broker Apache ActiveMQ Service
After=network.target
RequiresMountsFor=<redacted>

[Service]
User=amq-broker
Group=amq-broker
Type=forking
EnvironmentFile=-/etc/sysconfig/amq-broker
PIDFile=/opt/amq/amq-broker/data/artemis.pid
ExecStart=/opt/amq/amq-broker/bin/artemis-service start
ExecStop=/opt/amq/amq-broker/bin/artemis-service stop
SuccessExitStatus = 0 143
RestartSec = 120
Restart = on-failure
LimitNOFILE=102642
TimeoutSec=600
ExecStartPost=/usr/bin/timeout 60 sh -c 'tail -n 15 -F /var/log/amq-broker/artemis.log | sed "/AMQ221010\\\\|AMQ221031\\\\|AMQ221007\\\\|AMQ221109\\\\|AMQ221000/ q" && /bin/sleep 10'


[Install]
WantedBy=multi-user.target
```
